// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckQEMU() {
  return window['go']['main']['App']['CheckQEMU']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function DeployModeA(arg1, arg2) {
  return window['go']['main']['App']['DeployModeA'](arg1, arg2);
}

export function DeployModeABatch(arg1, arg2) {
  return window['go']['main']['App']['DeployModeABatch'](arg1, arg2);
}

export function DeployModeB(arg1) {
  return window['go']['main']['App']['DeployModeB'](arg1);
}

export function DeployModeBBatch(arg1) {
  return window['go']['main']['App']['DeployModeBBatch'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDiskList() {
  return window['go']['main']['App']['GetDiskList']();
}

export function GetFirmwareList() {
  return window['go']['main']['App']['GetFirmwareList']();
}

export function GetUniBootReleaseInfo() {
  return window['go']['main']['App']['GetUniBootReleaseInfo']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SyncUniBootFirmware() {
  return window['go']['main']['App']['SyncUniBootFirmware']();
}
