// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {config} from '../models';
import {main} from '../models';

export function CheckUpdate():Promise<updater.UpdateStatus>;

export function GetConfig():Promise<config.AppConfig>;

export function GetHelloInfo():Promise<main.HelloInfo>;

export function GetSystemInfo():Promise<main.SystemInfo>;

export function Greet(arg1:string):Promise<string>;

export function OpenURL(arg1:string):Promise<void>;

export function SaveConfig(arg1:config.AppConfig):Promise<void>;

export function TestNetwork(arg1:string):Promise<main.NetworkTestResult>;
