// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckQEMU() {
  return window['go']['main']['App']['CheckQEMU']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function DeployModeA(arg1) {
  return window['go']['main']['App']['DeployModeA'](arg1);
}

export function DeployModeB(arg1) {
  return window['go']['main']['App']['DeployModeB'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDiskList() {
  return window['go']['main']['App']['GetDiskList']();
}
