// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {qemu} from '../models';
import {updater} from '../models';
import {installer} from '../models';
import {config} from '../models';
import {disk} from '../models';
import {firmware} from '../models';

export function CheckQEMU():Promise<qemu.QEMUStatus>;

export function CheckUpdate():Promise<updater.UpdateStatus>;

export function DeployModeA(arg1:string,arg2:string):Promise<installer.DeployResult>;

export function DeployModeABatch(arg1:Array<string>,arg2:string):Promise<Array<installer.DeployResult>>;

export function DeployModeB(arg1:string,arg2:string):Promise<installer.DeployResult>;

export function DeployModeBBatch(arg1:Array<string>,arg2:string):Promise<Array<installer.DeployResult>>;

export function GetConfig():Promise<config.AppConfig>;

export function GetDiskList():Promise<Array<disk.DiskInfo>>;

export function GetFirmwareList():Promise<Array<firmware.FirmwareMapping>>;

export function GetUniBootReleaseInfo():Promise<firmware.UniBootReleaseInfo>;

export function SaveConfig(arg1:config.AppConfig):Promise<void>;

export function SyncUniBootFirmware():Promise<firmware.UniBootReleaseInfo>;
